### ISSUE TITLE
Pedagogy - Leaps in Knowledge

### ISSUE THREAD

**Issue by JM-Hansen** [learn-co-curriculum/dsc-scraping-concerts-lab#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)
- 

### Source

```

```

## What OS Are You Using?

- [ x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

## Any Additional Context?

Many of the labs presented do a good job of building on both the lessons in Illumidesk and the Flex Lectures
with Greg.  While the learning curve is steep, there have been a few lengthier labs that call for far more skills and knowledge than FlatIron presents making it very difficult to traverse that steep learning curve. This particular lab is one of those. It would be helpful to either break up this lab into two different labs with more skills acquisition along the way or to select a different less complex sample website to work from.  There just needs to be a bit smoother glide on that steep learning curve, this lab feels kind of like there is a chasm to leap along the way.

**Comment by bpurdy-ds** [comment]
Phase 1, Topic 10

**Comment by bpurdy-ds** [comment]
I have added hints along the way so the students don't get lost along the way. Closed with commit: https://github.com/learn-co-curriculum/dsc-scraping-concerts-lab/issues/3#issue-1268418306
